### ISSUE TITLE
The function [close] doesn't exist in the string

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/spreadsheet-cfml#311] opened 2022-11-17 02:22 UTC
We're suddenly having problems with csv files.  The same file saved as an xls/xlsx works properly.  Oddly, it affects only Linux, in this case, the Ortus docker container.  The files import fine on my windows workstation.  It has been working fine for months, and these containers are built from the ground up every time we push new code.  I don't know what has changed.

Here's a stack trace:

![image](https://user-images.githubusercontent.com/12553953/202338435-a3dc57b8-91c8-4f85-ac34-9aac8703e111.png)

**Comment by cfsimplicity** [comment] 2022-11-17 12:48
Version 3.7.0 did include some CSV improvements which seem to be causing that exception according to your trace. The library's tests all passed though and like you I can't replicate it locally. I even spun up a vanilla Ortus docker container but that worked fine for me as well, as did an Alpine Linux variation. I'm not a docker expert, but what exact image tag are you using and are you customising it in any way?

The error seems to suggest that the `java.io.fileReader` object is a string, but I don't understand how that can be.

Anyway, I went back to the Commons CSV docs and it seems that closing that object isn't actually necessary since I'm closing the parser as well. So I've removed that operation and published it as v3.7.1. Please give that a go and let me know the result.

**Comment by Daemach** [comment] 2022-11-17 13:03
Thanks, Julian.  Below is my dockerfile.  We ran into a container bug that forced me to drop back to the base commandbox image and force a specific version of Lucee.

```
FROM ortussolutions/commandbox

ENV BOX_SERVER_APP_CFENGINE=lucee@5.3.9+166

COPY ./ $APP_DIR
RUN rm -rf build
RUN box install --production
RUN ${BUILD_DIR}/util/warmup-server.sh
```

**Comment by Daemach** [comment] 2022-11-17 13:52
I just tried it, and no joy still.  What is a good version number before these changes?  I'll try rolling back for now.

**Comment by cfsimplicity** [comment] 2022-11-17 13:58
[3.6.1](https://github.com/cfsimplicity/spreadsheet-cfml/releases/tag/v3.6.1) was the previous release.

But I'd prefer to sort out the current version if possible. Can you post the stack trace you're now getting from 3.7.1?

**Comment by Daemach** [comment] 2022-11-17 14:20
I hear that.

There is no good place to test it now - I need to get a docker staging server set up.  I can try to test it later, but we're in production, so I need to get this working.

**Comment by cfsimplicity** [comment] 2022-11-17 14:27
Understood, but if you've still got the error logs from having tried 3.7.1 in prod that would be great so I can see what triggered it having removed that extra `close()` method.

Otherwise, we'll leave this open so you can come back to it when you can.

**Comment by Daemach** [comment] 2022-11-17 14:56
the problem is that our containers are load balanced, and I can only get to them using docker-exec.  But I connected to all three servers and was able to get a stack trace which shows a different issue now which may be on my end.  I'm looking at it.  

spreadsheet-cfml should be able to read from a lucee virtual file system right?  ram://temp.csv?

**Comment by Daemach** [comment] 2022-11-17 15:27
Oddly this has been working fine until now...  But I'll try that.

**Comment by cfsimplicity** [comment] 2022-11-17 15:35
Apologies, you're right! I've just tested with an old version and VFS works. So this is a regression which I'll try and sort out.

**Comment by cfsimplicity** [comment] 2022-11-17 15:41
OK I see now: previously if you specified a filepath, the library used CFML `FileRead()` to convert it to a string and then proceed as if you'd passed a string. But the performance improvement was to avoid that intermediate step by using the native Commons CSV java methods for parsing files directly.

**Comment by Daemach** [comment] 2022-11-17 15:52
Gotcha. This may have ramifications.  I’m moving everything to CBFS soon (https://github.com/coldbox-modules/cbfs). Might make a good coldbox.cfc module setting, but adding documentation would be good.

**Closed** 2022-11-17 16:12 UTC

**Comment by cfsimplicity** [comment] 2022-11-17 16:13
OK, 3.7.2 is live on Forgebox with the regression fix.

**Comment by Daemach** [comment] 2022-11-17 16:21
Sounds good.  I think we may always have to use the file read method, as we may be moving more data to S3 too.

**Comment by cfsimplicity** [comment] 2022-11-17 16:29
With 3.7.2 you won't need to for `csvToQuery()`: it uses `FileRead()` internally again.

**Comment by Daemach** [comment] 2022-11-17 19:30
Yes, but that may not work with CBFS - it has its own read/write methods which probably use fileRead() under the hood for local drives, but a different method for S3/FTP, etc.
